### Batch GD Arka Planı: Matrislerle Adım Adım Manuel Hesaplama

Algoritmanın tüm veri seti yerine sadece 2 örnek ($m=2$) için ilk adımda ne yaptığını elle hesaplama:
*   **1. Örnek:** $x=2$, Gerçek değer $y=5$
*   **2. Örnek:** $x=3$, Gerçek değer $y=7$

Öğrenme oranı ($\eta$) = $0.1$ alınır ve model tahmin yapmaya rastgele **$\theta_0 = 1$ (Bias)** ve **$\theta_1 = 1$ (Ağırlık)** ile başlar.

#### Adım 1: Başlangıç Matrislerini Kurma
Özelliklere ($x$) bias için bir sütun $1$ ekleyerek $\mathbf{X}_b$ matrisi oluşturulur:

$$ \mathbf{X}_b = \begin{bmatrix} 1 & 2 \\ 1 & 3 \end{bmatrix}, \quad \mathbf{y} = \begin{bmatrix} 5 \\ 7 \end{bmatrix}, \quad \boldsymbol{\theta} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} $$

#### Adım 2: Tahmin Yapma (Hypothesis) $\rightarrow \mathbf{X}_b \cdot \boldsymbol{\theta}$
Modelin ilk tahmini, veri matrisi ile ağırlık vektörünün çarpılmasıdır (Satır $\times$ Sütun):

$$ \mathbf{\hat{y}} = \begin{bmatrix} 1 & 2 \\ 1 & 3 \end{bmatrix} \begin{bmatrix} 1 \\ 1 \end{bmatrix} = \begin{bmatrix} (1 \cdot 1) + (2 \cdot 1) \\ (1 \cdot 1) + (3 \cdot 1) \end{bmatrix} = \begin{bmatrix} 3 \\ 4 \end{bmatrix} $$
*(Yani ilk tahminde model 5 yerine 3, 7 yerine 4 sonucunu buldu).*

#### Adım 3: Hata Hesaplama (Error) $\rightarrow \mathbf{\hat{y}} - \mathbf{y}$
Tahminlerden gerçek $\mathbf{y}$ değerler çıkarılarak hata (farkı) bulunur:

$$ \text{Hata} = \begin{bmatrix} 3 \\ 4 \end{bmatrix} - \begin{bmatrix} 5 \\ 7 \end{bmatrix} = \begin{bmatrix} -2 \\ -3 \end{bmatrix} $$

#### Adım 4: Gradyanları (Kısmi Türevleri) Bulma $\rightarrow \frac{2}{m} \mathbf{X}_b^T \cdot \text{Hata}$
Hangi parametrenin ne kadar değiştirileceğini bulmak için $\mathbf{X}_b$ matrisinin **transpozu (devriğini)** alınır. Transpoz sayesinde parametrelerin verileri birbirine karışmaz, her parametre kendi maliyetini görür. ($m=2$ olduğu için baştaki $2/m$ çarpanı $1$ olur. Bir nevi uygunluğunu sağlama?):

$$ \mathbf{X}_b^T = \begin{bmatrix} 1 & 1 \\ 2 & 3 \end{bmatrix} $$

$$ \text{Gradyan} = 1 \cdot \begin{bmatrix} 1 & 1 \\ 2 & 3 \end{bmatrix} \begin{bmatrix} -2 \\ -3 \end{bmatrix} = \begin{bmatrix} (1 \cdot -2) + (1 \cdot -3) \\ (2 \cdot -2) + (3 \cdot -3) \end{bmatrix} = \begin{bmatrix} -5 \\ -13 \end{bmatrix} $$

*Gradyanların negatif çıkması, tanjantın geniş açı (2. bölge) yapmasından dolayıdır ve hatayı azaltmak için $\theta$ değerlerinin BÜYÜTÜLMESİ gerektiğini söyler.*

#### Adım 5: Parametreleri Güncelleme $\rightarrow \boldsymbol{\theta}_{\text{yeni}} = \boldsymbol{\theta} - \eta \cdot \text{Gradyan}$
$$ \boldsymbol{\theta}_{\text{yeni}} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} - 0.1 \begin{bmatrix} -5 \\ -13 \end{bmatrix} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} - \begin{bmatrix} -0.5 \\ -1.3 \end{bmatrix} = \begin{bmatrix} 1.5 \\ 2.3 \end{bmatrix} $$

**Sonuç:** Tek bir matris iterasyonu ile parametreler $\mathbf{b = 1.5}$ ve $\mathbf{a = 2.3}$'e yükseldi

In [2]:
import numpy as np

In [3]:
# ornegin kodla dogurlanmasi
X_manual = np.array([[1, 2],
                    [1, 3]])
y_manual = np.array([[5],
                    [7]])
theta_manual = np.array([[1],
                         [1]])

eta_manual = 0.1
m_manual = 2

# tahmin
y_hat = X_manual.dot(theta_manual)
# hata
error = y_hat - y_manual
# gradyan - transpoz carpim ile ayiklama
gradients_manual = 2/m_manual * X_manual.T.dot(error)
# guncelleme
theta_new = theta_manual - eta_manual * gradients_manual

In [7]:
print("--- Manuel SGD Hesabının Python Çıktıları ---")
print("Seçilen Örnek Özellikleri (xi):\n", xi)
print("Seçilen Örnek Gerçek Değeri (yi):\n", yi)
print("Modelin Tahmini (y_hat_sgd):\n", y_hat_sgd)
print("Hata Değeri:\n", error_sgd)
print("Hesaplanan SGD Gradyanları:\n", gradients_sgd)
print("Güncellenmiş Yeni Thetalar (theta_new_sgd):\n", theta_new_sgd)

--- Manuel SGD Hesabının Python Çıktıları ---
Seçilen Örnek Özellikleri (xi):
 [[1 2]]
Seçilen Örnek Gerçek Değeri (yi):
 [[5]]
Modelin Tahmini (y_hat_sgd):
 [[3]]
Hata Değeri:
 [[-2]]
Hesaplanan SGD Gradyanları:
 [[-4]
 [-8]]
Güncellenmiş Yeni Thetalar (theta_new_sgd):
 [[1.4]
 [1.8]]


- Matrisleri Kurma: Giriş verileri ($X_b$, $y$) ve başlangıç katsayıları ($\theta$) tanımlanır.
- Tahmin Yapma: Mevcut katsayılar verilerle çarpılarak ($\mathbf{X}_b \cdot \boldsymbol{\theta}$) modelin tahminleri hesaplanır.
- Hata Hesaplama: Tahminlerden gerçek değerler çıkarılarak ($\mathbf{\hat{y}} - \mathbf{y}$) sapma miktarı bulunur.
Transpoz ile Ayıklama: Özelliklerin birbirine karışmaması için veri matrisinin devriği ($\mathbf{X}_b^T$) alınır.
- Gradyanları Bulma: Devrik matris ile hata çarpılarak her parametrenin eğimi (tanjantı) elde edilir.
- Parametreleri Güncelleme: Bulunan eğim yönünün tersine gidilerek yeni ve daha zeki katsayılar ($\boldsymbol{\theta}_{\text{yeni}}$) kaydedilir.

### SGD Arka Planı: Matrislerle Adım Adım Manuel Hesaplama

Algoritmanın tüm veri seti yerine her adımda **rastgele seçilen tek bir örnek** ($m=1$) için ne yaptığını elle hesaplama:
*   **Seçilen Rastgele Örnek:** $x=2$, Gerçek değer $y=5$ (Not: Diğer örnek bu adıma dahil edilmez).
*   Öğrenme oranı ($\eta$) = $0.1$ alınır ve model tahmin yapmaya rastgele **$\theta_0 = 1$ (Bias)** ve **$\theta_1 = 1$ (Ağırlık)** ile başlar.

#### Adım 1: Başlangıç Matrislerini Kurma
Seçilen tek örneğin özelliklerine bias için $1$ ekleyerek $\mathbf{x}_i$ satır vektörünü oluştururuz. Hedef değer $y_i$ ve parametreler $\boldsymbol{\theta}$ şu şekildedir:

$$ \mathbf{x}_i = \begin{bmatrix} 1 & 2 \end{bmatrix}, \quad y_i = \begin{bmatrix} 5 \end{bmatrix}, \quad \boldsymbol{\theta} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} $$

#### Adım 2: Tahmin Yapma (Hypothesis) $\rightarrow \mathbf{x}_i \cdot \boldsymbol{\theta}$
Modelin bu tek örnek için tahmini, satır vektörü ile ağırlık vektörünün çarpılmasıdır (Satır $\times$ Sütun):

$$ \hat{y}_i = \begin{bmatrix} 1 & 2 \end{bmatrix} \begin{bmatrix} 1 \\ 1 \end{bmatrix} = \begin{bmatrix} (1 \cdot 1) + (2 \cdot 1) \end{bmatrix} = \begin{bmatrix} 3 \end{bmatrix} $$
*(Yani model bu örnek için 5 yerine 3 sonucunu buldu).*

#### Adım 3: Hata Hesaplama (Error) $\rightarrow \hat{y}_i - y_i$
Tahminden gerçek $y_i$ değeri çıkarılarak tek bir hata değeri bulunur:

$$ \text{Hata} = \begin{bmatrix} 3 \end{bmatrix} - \begin{bmatrix} 5 \end{bmatrix} = \begin{bmatrix} -2 \end{bmatrix} $$

#### Adım 4: Gradyanları (Kısmi Türevleri) Bulma $\rightarrow 2 \cdot \mathbf{x}_i^T \cdot \text{Hata}$
Tek örnek seçildiğinde ($m=1$), formülün başındaki $\frac{2}{m}$ çarpanı doğrudan $2$ olur. $\mathbf{x}_i$ vektörünün **transpozu (devriği)** alınarak hata skaleri ile çarpılır:

$$ \mathbf{x}_i^T = \begin{bmatrix} 1 \\ 2 \end{bmatrix} $$

$$ \text{Gradyan} = 2 \cdot \begin{bmatrix} 1 \\ 2 \end{bmatrix} \begin{bmatrix} -2 \end{bmatrix} = \begin{bmatrix} 2 \cdot 1 \cdot -2 \\ 2 \cdot 2 \cdot -2 \end{bmatrix} = \begin{bmatrix} -4 \\ -8 \end{bmatrix} $$

*Gradyanların negatif çıkması, tanjantın geniş açı (2. bölge) yapmasından dolayıdır ve hatayı azaltmak için $\theta$ değerlerinin BÜYÜTÜLMESİ gerektiğini söyler.*

#### Adım 5: Parametreleri Güncelleme $\rightarrow \boldsymbol{\theta}_{\text{yeni}} = \boldsymbol{\theta} - \eta \cdot \text{Gradyan}$
$$ \boldsymbol{\theta}_{\text{yeni}} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} - 0.1 \begin{bmatrix} -4 \\ -8 \end{bmatrix} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} - \begin{bmatrix} -0.4 \\ -0.8 \end{bmatrix} = \begin{bmatrix} 1.4 \\ 1.8 \end{bmatrix} $$

**Sonuç:** Sadece tek bir rastgele örnek kullanılarak parametreler $\mathbf{b = 1.4}$ ve $\mathbf{a = 1.8}$'e yükseldi. Algoritma bir sonraki adımda yine rastgele başka bir örnek seçerek bu işlemi tekrarlayacaktır.

---

### Kısaca Yapılan İşlemlerin Özeti:
*   **Örnek Seçimi:** Tüm veri kümesinden rastgele tek bir veri noktası ($\mathbf{x}_i$, $y_i$) çekilir.
*   **Tahmin Yapma:** Seçilen verinin özellikleri mevcut katsayılarla çarpılarak ($\mathbf{x}_i \cdot \boldsymbol{\theta}$) tek bir tahmin üretilir.
*   **Hata Hesaplama:** Üretilen tahminden verinin gerçek değeri çıkarılarak sapma miktarı bulunur.
*   **Transpoz ile Ayıklama:** Hatanın parametrelere doğru dağılması için tekil veri vektörünün devriği ($\mathbf{x}_i^T$) alınır.
*   **Gradyanları Bulma:** Devrik vektör, hata payı ve $2$ kat sayısı ile çarpılarak parametrelerin o anki eğimleri (tanjantları) hesaplanır.
*   **Parametreleri Güncelleme:** Geniş açılı (negatif) eğimin ters yönüne doğru gidilerek katsayılar büyütülür ve $\boldsymbol{\theta}_{\text{yeni}}$ elde edilir.

In [5]:
# SGD manuel orneginin dogrulanmasi
X_manual = np.array([[1,2],[1,3]])
Y_manual = np.array([[5], [7]])
theta_manual = np.array([[1],[1]])

eta_manual = 0.1

# SGD icin sadece secilen 1. ornegin alinmasi (x=2, y=5)
xi = X_manual[0:1]  #[[1,2]]
yi = y_manual[0:1]  #[[5]]

# tahmin - tek ornek icin
y_hat_sgd = xi.dot(theta_manual)

# hata
error_sgd = y_hat_sgd - yi
# gradyan (m=1 oldugu icin bastaki carpan sadece 2'dir)
gradients_sgd = 2 * xi.T.dot(error_sgd)

# guncelleme
theta_new_sgd = theta_manual - eta_manual * gradients_sgd

In [8]:
print("--- Manuel SGD Hesabının Python Çıktıları ---")
print("Seçilen Örnek Özellikleri (xi):\n", xi)
print("Seçilen Örnek Gerçek Değeri (yi):\n", yi)
print("Modelin Tahmini (y_hat_sgd):\n", y_hat_sgd)
print("Hata Değeri:\n", error_sgd)
print("Hesaplanan SGD Gradyanları:\n", gradients_sgd)
print("Güncellenmiş Yeni Thetalar (theta_new_sgd):\n", theta_new_sgd)

--- Manuel SGD Hesabının Python Çıktıları ---
Seçilen Örnek Özellikleri (xi):
 [[1 2]]
Seçilen Örnek Gerçek Değeri (yi):
 [[5]]
Modelin Tahmini (y_hat_sgd):
 [[3]]
Hata Değeri:
 [[-2]]
Hesaplanan SGD Gradyanları:
 [[-4]
 [-8]]
Güncellenmiş Yeni Thetalar (theta_new_sgd):
 [[1.4]
 [1.8]]


## 3. Mini-batch Gradient Descent

Ne Batch GD gibi tüm veri setini bekler, ne de SGD gibi tek bir örneğe bakıp kararsızca salınım yapar. Veriyi **küçük gruplara (mini-batch)** böler ve her adımda bir grubu işler.

*   **Avantajı:** GPU (ekran kartı) kullanan donanımlarda matris işlemlerini paralel yaparak müthiş hızlanır. SGD'den daha kararlı ilerler.
*   **Dezavantajı:** Grup boyutu (Batch Size) adı verilen yeni bir hiperparametre seçmek gerekir (Genelde 16, 32, 64 seçilir).

### Mini-batch GD Arka Planı: Matrislerle Adım Adım Manuel Hesaplama

Algoritmanın tüm veri seti yerine o adımda seçilen **2 örnekten oluşan bir grup** ($m_{\text{batch}}=2$) için ne yaptığını elle hesaplama:
*   **Seçilen Grup (Batch):** 
    *   1. Örnek: $x=2$, Gerçek değer $y=5$
    *   2. Örnek: $x=3$, Gerçek değer $y=7$
*   Öğrenme oranı ($\eta$) = $0.1$ alınır ve model tahmin yapmaya rastgele **$\theta_0 = 1$ (Bias)** ve **$\theta_1 = 1$ (Ağırlık)** ile başlar.

#### Adım 1: Başlangıç Matrislerini Kurma
Gruptaki örneklerin özelliklerine bias için $1$ ekleyerek $\mathbf{X}_{\text{batch}}$ matrisini oluştururuz:

$$ \mathbf{X}_{\text{batch}} = \begin{bmatrix} 1 & 2 \\ 1 & 3 \end{bmatrix}, \quad \mathbf{y}_{\text{batch}} = \begin{bmatrix} 5 \\ 7 \end{bmatrix}, \quad \boldsymbol{\theta} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} $$

#### Adım 2: Tahmin Yapma (Hypothesis) $\rightarrow \mathbf{X}_{\text{batch}} \cdot \boldsymbol{\theta}$
$$ \mathbf{\hat{y}}_{\text{batch}} = \begin{bmatrix} 1 & 2 \\ 1 & 3 \end{bmatrix} \begin{bmatrix} 1 \\ 1 \end{bmatrix} = \begin{bmatrix} (1 \cdot 1) + (2 \cdot 1) \\ (1 \cdot 1) + (3 \cdot 1) \end{bmatrix} = \begin{bmatrix} 3 \\ 4 \end{bmatrix} $$

#### Adım 3: Hata Hesaplama (Error) $\rightarrow \mathbf{\hat{y}}_{\text{batch}} - \mathbf{y}_{\text{batch}}$
$$ \text{Hata} = \begin{bmatrix} 3 \\ 4 \end{bmatrix} - \begin{bmatrix} 5 \\ 7 \end{bmatrix} = \begin{bmatrix} -2 \\ -3 \end{bmatrix} $$

#### Adım 4: Gradyanları Bulma $\rightarrow \frac{2}{m_{\text{batch}}} \mathbf{X}_{\text{batch}}^T \cdot \text{Hata}$
Grup boyutu 2 ($m_{\text{batch}}=2$) olduğu için baştaki çarpan $\frac{2}{2} = 1$ olur:

$$ \text{Gradyan} = 1 \cdot \begin{bmatrix} 1 & 1 \\ 2 & 3 \end{bmatrix} \begin{bmatrix} -2 \\ -3 \end{bmatrix} = \begin{bmatrix} -5 \\ -13 \end{bmatrix} $$

#### Adım 5: Parametreleri Güncelleme $\rightarrow \boldsymbol{\theta}_{\text{yeni}} = \boldsymbol{\theta} - \eta \cdot \text{Gradyan}$
$$ \boldsymbol{\theta}_{\text{yeni}} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} - 0.1 \begin{bmatrix} -5 \\ -13 \end{bmatrix} = \begin{bmatrix} 1.5 \\ 2.3 \end{bmatrix} $$

*(Not: Bu minik senaryoda toplam verimiz zaten 2 örnekten oluştuğu için Mini-batch hesabı matematiksel olarak ilk adımdaki Batch GD ile aynı sonuçları vermiştir. Gerçek hayatta 10.000 veriden 32'şerli gruplar seçilerek yapılır).*

---

### Kısaca Yapılan İşlemlerin Özeti:
*   **Grup Seçimi:** Tüm veri kümesinden belirlenen `batch_size` kadar rastgele bir veri grubu ($\mathbf{X}_{\text{batch}}$, $\mathbf{y}_{\text{batch}}$) çekilir.
*   **Tahmin Yapma:** Seçilen grubun özellikleri mevcut katsayılarla çarpılarak grubun toplu tahminleri hesaplanır.
*   **Hata Hesaplama:** Tahminlerden grubun gerçek değerleri çıkarılarak gruptaki her örneğin sapma miktarı bulunur.
*   **Transpoz ile Ayıklama:** Hataların parametrelere doğru dağılması ve birbirine karışmaması için grup matrisinin devriği ($\mathbf{X}_{\text{batch}}^T$) alınır.
*   **Gradyanları Bulma:** Devrik matris ile hata vektörü çarpılıp grup boyutuna bölünerek ($\frac{2}{m_{\text{batch}}}$) ortalama yön vektörü hesaplanır.
*   **Parametreleri Güncelleme:** Eğim yönünün tersine gidilerek yeni katsayılar ($\boldsymbol{\theta}_{\text{yeni}}$) kaydedilir.

In [9]:
# Mibi-batch manuel orneginin kodla dogrulamasi

# 2 boyutlu baslangic matrisi
X_manuel = np.array([[1,2],[1,3]])
y_manual = np.array([[5],[7]])
theta_manual = np.array([[1],[1]])

eta_manual = 0.1
m_batch = 2 # secilen grup boyutu - satir sayisi

# baslangic matrislerini kurma - ilk grubu dilimleyerek alma
X_batch = X_manual[0:2]
y_batch = y_manual[0:2]


# tahmin yapma
y_hat_mb = X_batch.dot(theta_manual)

# hata hesaplama - error
error_mb = y_hat_mb - y_batch

# gradyanlari bulma ve guncelleme
# grup boyutu 2 oldugu icin 2/m_batch carpani 2/2 = 1 olur.
gradients_mb = 2/m_batch * X_batch.T.dot(error_mb)
theta_new_mb = theta_manual - eta_manual * gradients_mb

In [10]:
print("--- Manuel Mini-batch Hesabının Python Çıktıları ---")
print("Grup Özellik Matrisi (X_batch):\n", X_batch)
print("Grup Gerçek Değerleri (y_batch):\n", y_batch)
print("Modelin Grup Tahminleri (y_hat_mb):\n", y_hat_mb)
print("Grup Hata Vektörü:\n", error_mb)
print("Hesaplanan Mini-batch Gradyanları:\n", gradients_mb)
print("Güncellenmiş Yeni Thetalar (theta_new_mb):\n", theta_new_mb)

--- Manuel Mini-batch Hesabının Python Çıktıları ---
Grup Özellik Matrisi (X_batch):
 [[1 2]
 [1 3]]
Grup Gerçek Değerleri (y_batch):
 [[5]
 [7]]
Modelin Grup Tahminleri (y_hat_mb):
 [[3]
 [4]]
Grup Hata Vektörü:
 [[-2]
 [-3]]
Hesaplanan Mini-batch Gradyanları:
 [[ -5.]
 [-13.]]
Güncellenmiş Yeni Thetalar (theta_new_mb):
 [[1.5]
 [2.3]]
